version: "3.9"

services:
  bot:
    build: .
    container_name: truecaller_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
